const cartData = [
  {
    id: 1,
    title: 'SHEIN SXY Floral Print Stand Neck Mesh Dress',
    image: '/images/cart/cart_1.webp',
    price: 8,
    oldPrice: 0,
    quantity: 1,
    color: 'Multicolor',
    size: 'S',
  },
  {
    id: 2,
    title: 'Contrast Lace Zipper Back Cami Wedding Dress',
    image: '/images/cart/cart_2.webp',
    price: 79,
    oldPrice: 0,
    quantity: 1,
    color: 'White',
    size: 'S',
  },
  {
    id: 3,
    title:
      'SHEIN BAE Draped Collar Chain Detail Crisscross Backless Ruched Cami Dress',
    image: '/images/cart/cart_3.webp',
    price: 11,
    oldPrice: 0,
    quantity: 1,
    color: 'Black',
    size: 'S',
  },
  {
    id: 4,
    title: 'SHEIN Belle Layered Fringe Trim Backless Sequin Halter Dress',
    image: '/images/cart/cart_4.webp',
    price: 35,
    oldPrice: 0,
    quantity: 3,
    color: 'Champagne',
    size: 'S',
  },
  {
    id: 5,
    title: 'Double Crazy Mesh Panel M-slit Hem Bustier Formal Dress',
    image: '/images/cart/cart_5.webp',
    price: 29,
    oldPrice: 0,
    quantity: 1,
    color: 'Red',
    size: 'S',
  },
  {
    id: 6,
    title: 'Double Crazy Contrast Mesh Split Thigh Bustier Cami Dress',
    image: '/images/cart/cart_6.jpg',
    price: 27,
    oldPrice: 0,
    quantity: 1,
    color: 'Purple',
    size: 'S',
  },
  {
    id: 7,
    title: 'Contrast Mesh Split Thigh Bustier Cami Dress',
    image: '/images/cart/cart_7.jpg',
    price: 27,
    oldPrice: 0,
    quantity: 1,
    color: 'Yellow',
    size: 'S',
  },
];

export default cartData;
